name: Ecommerce Microservice GRPC

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

  workflow_dispatch:

jobs:
  # API GATEWAY
  api-gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-gateway

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Setup api gateway
      - name: Setup Project ApiGateway
        working-directory: ./api-gateway
        run: yarn && yarn format && yarn build

  # AUTH MICRO
  auth-micro:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./auth-micro

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Setup auth micro
      - name: Setup Project AuthMicro
        working-directory: ./auth-micro
        run: yarn && yarn format && yarn build

  # JOBS MICRO
  jobs-micro:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jobs-micro

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Setup jobs micro
      - name: Setup Project JobsMicro
        working-directory: ./jobs-micro
        run: yarn && yarn format && yarn build

  # USER MICRO
  user-micro:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-micro

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Setup user micro
      - name: Setup Project UserMicro
        working-directory: ./user-micro
        run: yarn && yarn format && yarn build

  # PRODUCT MICRO
  product-micro:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./product-micro

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Setup user micro
      - name: Setup Project ProductMicro
        working-directory: ./product-micro
        run: yarn && yarn format && yarn build
